version: "3.8"

services:
  
  accounts:
    image: strazhkoe/accounts:latest
    mem_limit: 700m
    ports:
      - "8080:8080"
    networks:
      - easybank-network
  
  loans:
    image: strazhkoe/loans
    mem_limit: 700m
    ports:
      - "8090:8090"
    networks:
      - easybank-network

  cards:
    image: strazhkoe/cards
    mem_limit: 700m
    ports:
      - "9000:9000"
    networks:
      - easybank-network

networks:
  easybank-network:   
  