version: "3.8"

services:

  configserver:
    image: strazhkoe/configserver
    mem_limit: 700m
    ports:
      - "8071:8071"
    networks:
      - easybank-network
  
  accounts:
    image: strazhkoe/accounts:latest
    mem_limit: 700m
    ports:
      - "8080:8080"
    networks:
      - easybank-network
    depends_on:
      - configserver
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
    environment:
      - SPRING_PROFILES_ACTIVE=default
      - SPRING_CONFIG_IMPORT=configserver:http://configserver:8071/
  
  loans:
    image: strazhkoe/loans
    mem_limit: 700m
    ports:
      - "8090:8090"
    networks:
      - easybank-network
    depends_on:
      - configserver
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
    environment:
      - SPRING_PROFILES_ACTIVE=default
      - SPRING_CONFIG_IMPORT=configserver:http://configserver:8071/

  cards:
    image: strazhkoe/cards
    mem_limit: 700m
    ports:
      - "9000:9000"
    networks:
      - easybank-network
    depends_on:
      - configserver
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
    environment:
      - SPRING_PROFILES_ACTIVE=default
      - SPRING_CONFIG_IMPORT=configserver:http://configserver:8071/

networks:
  easybank-network:   
  